# Taken from https://github.com/vicky5124/lavasnek_rs/blob/master/.github/workflows/release.yml

name: Release to to PyPi and GitHub

on:
  push:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} - ${{ matrix.vers }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        vers: [i686, aarch64, auto64]
        include:
          - vers: i686
            os: ubuntu-latest
          - vers: aarch64
            os: ubuntu-latest
          - vers: auto64
            os: ubuntu-latest
          - vers: arm64
            os: macos-latest
          - vers: auto64
            os: macos-latest
          - vers: auto64
            os: windows-latest

    env:
      CIBW_ARCHS_LINUX: ${{ matrix.vers }}
      CIBW_ARCHS_MACOS: ${{ matrix.vers }}
      CIBW_ARCHS_WINDOWS: ${{ matrix.vers }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up QEMU
        if: runner.os == 'Linux'
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: messense/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          args: --release -o dist

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install Dependencies
        run: pip install poetry
      - name:  Build sdist
        run: |
          poetry build
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  release:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
